/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Principal;

import Vistas.Facturador.NotasCreditoDebito;
import java.awt.Dimension;
import javax.swing.JComponent;

/**
 *
 * @author PC02
 */
public class Principal_Facturador extends javax.swing.JInternalFrame {
private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
private Dimension DimensionBarra = null;
    /**
     * Creates new form Principal_Facturador
     */
    public Principal_Facturador() {
        initComponents();
        QuitarLaBarraTitulo();
    }

    public void QuitarLaBarraTitulo(){ 
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane(); 
        DimensionBarra = Barra.getPreferredSize(); 
        Barra.setSize(0,0); 
        Barra.setPreferredSize(new Dimension(0,0)); 
        repaint(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelSesion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lblIDSESION = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNotaDebito = new javax.swing.JButton();
        NotaCreditoç = new javax.swing.JButton();
        btnComunicacionBaja = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Facturador SUNAT");

        PanelSesion.setBackground(new java.awt.Color(255, 51, 51));
        PanelSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelSesionMouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salir");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelSesionLayout = new javax.swing.GroupLayout(PanelSesion);
        PanelSesion.setLayout(PanelSesionLayout);
        PanelSesionLayout.setHorizontalGroup(
            PanelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSesionLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        PanelSesionLayout.setVerticalGroup(
            PanelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("ID de Sesión Actual");

        lblIDSESION.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblIDSESION.setForeground(new java.awt.Color(255, 255, 255));
        lblIDSESION.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIDSESION, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(PanelSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(lblIDSESION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(127, 140, 141));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/icons8-Atrás-30.png"))); // NOI18N
        jLabel1.setText("Volver");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        btnNotaDebito.setBackground(new java.awt.Color(102, 102, 102));
        btnNotaDebito.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnNotaDebito.setForeground(new java.awt.Color(51, 51, 51));
        btnNotaDebito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/icons8-Etiqueta de precio-64.png"))); // NOI18N
        btnNotaDebito.setText("Nota de Débito");
        btnNotaDebito.setContentAreaFilled(false);
        btnNotaDebito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotaDebito.setFocusPainted(false);
        btnNotaDebito.setFocusable(false);
        btnNotaDebito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotaDebito.setIconTextGap(30);
        btnNotaDebito.setVerifyInputWhenFocusTarget(false);
        btnNotaDebito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotaDebito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotaDebitoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNotaDebitoMouseEntered(evt);
            }
        });
        btnNotaDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaDebitoActionPerformed(evt);
            }
        });

        NotaCreditoç.setBackground(new java.awt.Color(102, 102, 102));
        NotaCreditoç.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        NotaCreditoç.setForeground(new java.awt.Color(51, 51, 51));
        NotaCreditoç.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/icons8-Etiqueta de precio-64.png"))); // NOI18N
        NotaCreditoç.setText("Nota de Crédito");
        NotaCreditoç.setContentAreaFilled(false);
        NotaCreditoç.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NotaCreditoç.setFocusPainted(false);
        NotaCreditoç.setFocusable(false);
        NotaCreditoç.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NotaCreditoç.setIconTextGap(30);
        NotaCreditoç.setVerifyInputWhenFocusTarget(false);
        NotaCreditoç.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        NotaCreditoç.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NotaCreditoçMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NotaCreditoçMouseEntered(evt);
            }
        });
        NotaCreditoç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaCreditoçActionPerformed(evt);
            }
        });

        btnComunicacionBaja.setBackground(new java.awt.Color(102, 102, 102));
        btnComunicacionBaja.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnComunicacionBaja.setForeground(new java.awt.Color(51, 51, 51));
        btnComunicacionBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/icons8-Etiqueta de precio-64.png"))); // NOI18N
        btnComunicacionBaja.setText("<html><center>Comunicación <br>de Baja </center></html>");
        btnComunicacionBaja.setContentAreaFilled(false);
        btnComunicacionBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComunicacionBaja.setFocusPainted(false);
        btnComunicacionBaja.setFocusable(false);
        btnComunicacionBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComunicacionBaja.setIconTextGap(30);
        btnComunicacionBaja.setVerifyInputWhenFocusTarget(false);
        btnComunicacionBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComunicacionBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComunicacionBajaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComunicacionBajaMouseEntered(evt);
            }
        });
        btnComunicacionBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComunicacionBajaActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(102, 102, 102));
        btnReportes.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(51, 51, 51));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/icons8-Etiqueta de precio-64.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setFocusPainted(false);
        btnReportes.setFocusable(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setIconTextGap(30);
        btnReportes.setVerifyInputWhenFocusTarget(false);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
        });
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NotaCreditoç, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnNotaDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnComunicacionBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNotaDebito, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(NotaCreditoç, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(btnComunicacionBaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSesionMouseEntered

    }//GEN-LAST:event_PanelSesionMouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        Principal.PaginasP.setSelectedIndex(0);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnNotaDebitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotaDebitoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotaDebitoMouseClicked

    private void btnNotaDebitoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotaDebitoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotaDebitoMouseEntered

    private void btnNotaDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaDebitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotaDebitoActionPerformed

    private void NotaCreditoçMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotaCreditoçMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaCreditoçMouseClicked

    private void NotaCreditoçMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotaCreditoçMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaCreditoçMouseEntered

    private void NotaCreditoçActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaCreditoçActionPerformed
        NotasCreditoDebito n=new NotasCreditoDebito();
        n.setVisible(true);
    }//GEN-LAST:event_NotaCreditoçActionPerformed

    private void btnComunicacionBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComunicacionBajaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComunicacionBajaMouseClicked

    private void btnComunicacionBajaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComunicacionBajaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComunicacionBajaMouseEntered

    private void btnComunicacionBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComunicacionBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComunicacionBajaActionPerformed

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesMouseClicked

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton NotaCreditoç;
    private javax.swing.JPanel PanelSesion;
    public static javax.swing.JButton btnComunicacionBaja;
    public static javax.swing.JButton btnNotaDebito;
    public static javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel lblIDSESION;
    // End of variables declaration//GEN-END:variables
}
