/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Caja;

/**
 *
 * @author MYS1
 */
public class Caja_Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Caja_Ventas
     */
    public Caja_Ventas() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        txtBusquedas = new javax.swing.JTextField();
        btnBuscarPaciente = new javax.swing.JButton();
        lbldetalle = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtape = new javax.swing.JLabel();
        panelMensaje = new javax.swing.JPanel();
        Mensaje4 = new javax.swing.JLabel();
        btnCorrectoSi = new javax.swing.JButton();
        btnCorrectoNo = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelCPT = new javax.swing.JPanel();
        txtgrupo = new javax.swing.JTextField();
        lTipoDoc = new javax.swing.JLabel();
        cbxTipoDocumento = new javax.swing.JComboBox();
        lDoc = new javax.swing.JLabel();
        lblNumeroDoc = new javax.swing.JLabel();
        lDoc1 = new javax.swing.JLabel();
        panelCPT1 = new javax.swing.JPanel();
        txtCPT = new javax.swing.JTextField();
        btnBuscarCPT = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_CPT = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false; //Disallow the editing of any cell
            }};
            panelNumeros = new javax.swing.JPanel();
            jLabel26 = new javax.swing.JLabel();
            panelSumaDetalle = new javax.swing.JPanel();
            jLabel39 = new javax.swing.JLabel();
            jLabel28 = new javax.swing.JLabel();
            txtTotal2 = new javax.swing.JLabel();
            txtTotal3 = new javax.swing.JLabel();
            txtTotal = new javax.swing.JLabel();
            txtTotal1 = new javax.swing.JLabel();
            panelEliminacion = new javax.swing.JPanel();
            btnEliminarDetalle = new javax.swing.JButton();
            noeli5 = new javax.swing.JButton();
            eli5 = new javax.swing.JButton();
            lDoc2 = new javax.swing.JLabel();
            panelCPT2 = new javax.swing.JPanel();
            txtgrupo1 = new javax.swing.JTextField();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jPanel1.setBackground(new java.awt.Color(41, 127, 184));
            jPanel1.setPreferredSize(new java.awt.Dimension(284, 684));

            jLabel57.setBackground(new java.awt.Color(255, 255, 255));
            jLabel57.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
            jLabel57.setForeground(new java.awt.Color(255, 255, 255));
            jLabel57.setText("<html>Ventas<span style=\"font-size:'14px'\"><br>Caja Central</br></span></html>");

            jPanel23.setBackground(new java.awt.Color(255, 255, 255));

            txtBusquedas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            txtBusquedas.setForeground(new java.awt.Color(51, 51, 51));
            txtBusquedas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            txtBusquedas.setBorder(javax.swing.BorderFactory.createCompoundBorder());
            txtBusquedas.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtBusquedasCaretUpdate(evt);
                }
            });
            txtBusquedas.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtBusquedasKeyTyped(evt);
                }
            });

            javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
            jPanel23.setLayout(jPanel23Layout);
            jPanel23Layout.setHorizontalGroup(
                jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel23Layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(txtBusquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel23Layout.setVerticalGroup(
                jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel23Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(txtBusquedas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            btnBuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/Búsqueda-27.png"))); // NOI18N
            btnBuscarPaciente.setContentAreaFilled(false);
            btnBuscarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBuscarPacienteActionPerformed(evt);
                }
            });

            lbldetalle.setForeground(new java.awt.Color(255, 255, 255));
            lbldetalle.setText("DNI, ID Venta");

            btnNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            btnNuevo.setForeground(new java.awt.Color(240, 240, 240));
            btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/Documento-32.png"))); // NOI18N
            btnNuevo.setText("Nuevo");
            btnNuevo.setContentAreaFilled(false);
            btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnNuevo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            btnNuevo.setIconTextGap(30);
            btnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            btnNuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnNuevoActionPerformed(evt);
                }
            });

            btnImprimir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            btnImprimir.setForeground(new java.awt.Color(240, 240, 240));
            btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/Imprimir-32.png"))); // NOI18N
            btnImprimir.setText("Imprimir");
            btnImprimir.setContentAreaFilled(false);
            btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnImprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            btnImprimir.setIconTextGap(30);
            btnImprimir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnImprimirActionPerformed(evt);
                }
            });

            btneliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            btneliminar.setForeground(new java.awt.Color(240, 240, 240));
            btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/Basura-32.png"))); // NOI18N
            btneliminar.setText("Anular");
            btneliminar.setContentAreaFilled(false);
            btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btneliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            btneliminar.setIconTextGap(30);
            btneliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            btneliminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btneliminarActionPerformed(evt);
                }
            });

            btnLista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            btnLista.setForeground(new java.awt.Color(240, 240, 240));
            btnLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/Orden de compra-32.png"))); // NOI18N
            btnLista.setText("Ventas de Hoy");
            btnLista.setContentAreaFilled(false);
            btnLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnLista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btnLista.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            btnLista.setIconTextGap(30);
            btnLista.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
            btnLista.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnListaActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbldetalle)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(19, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbldetalle)
                    .addGap(21, 21, 21)
                    .addComponent(btnNuevo)
                    .addGap(18, 18, 18)
                    .addComponent(btnImprimir)
                    .addGap(18, 18, 18)
                    .addComponent(btneliminar)
                    .addGap(18, 18, 18)
                    .addComponent(btnLista)
                    .addContainerGap(124, Short.MAX_VALUE))
            );

            jPanel2.setBackground(new java.awt.Color(43, 43, 43));
            jPanel2.setPreferredSize(new java.awt.Dimension(405, 113));

            txtape.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            txtape.setForeground(new java.awt.Color(255, 255, 255));
            txtape.setText("Nueva Venta");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtape)
                    .addContainerGap(77, Short.MAX_VALUE))
            );

            panelMensaje.setBackground(new java.awt.Color(255, 51, 51));

            Mensaje4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
            Mensaje4.setForeground(new java.awt.Color(255, 255, 255));
            Mensaje4.setText("Cancelar la venta ?");

            btnCorrectoSi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            btnCorrectoSi.setForeground(new java.awt.Color(240, 240, 240));
            btnCorrectoSi.setText("Si");
            btnCorrectoSi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
            btnCorrectoSi.setContentAreaFilled(false);
            btnCorrectoSi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnCorrectoSi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnCorrectoSi.setIconTextGap(30);
            btnCorrectoSi.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCorrectoSiActionPerformed(evt);
                }
            });
            btnCorrectoSi.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    btnCorrectoSiKeyPressed(evt);
                }
            });

            btnCorrectoNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            btnCorrectoNo.setForeground(new java.awt.Color(240, 240, 240));
            btnCorrectoNo.setText("No");
            btnCorrectoNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
            btnCorrectoNo.setContentAreaFilled(false);
            btnCorrectoNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnCorrectoNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnCorrectoNo.setIconTextGap(30);
            btnCorrectoNo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCorrectoNoActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout panelMensajeLayout = new javax.swing.GroupLayout(panelMensaje);
            panelMensaje.setLayout(panelMensajeLayout);
            panelMensajeLayout.setHorizontalGroup(
                panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMensajeLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(Mensaje4)
                    .addGap(43, 43, 43)
                    .addComponent(btnCorrectoSi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnCorrectoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            panelMensajeLayout.setVerticalGroup(
                panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMensajeLayout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addGroup(panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCorrectoSi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCorrectoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
                .addComponent(Mensaje4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            jTabbedPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
            jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
            jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
            jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N

            jPanel3.setBackground(new java.awt.Color(255, 255, 255));

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 641, Short.MAX_VALUE)
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 403, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("tab1", jPanel3);

            jPanel4.setBackground(new java.awt.Color(255, 255, 255));

            jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
            jLabel2.setText("Cliente");

            panelCPT.setBackground(new java.awt.Color(255, 255, 255));
            panelCPT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

            txtgrupo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            txtgrupo.setForeground(new java.awt.Color(51, 51, 51));
            txtgrupo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            txtgrupo.setBorder(null);
            txtgrupo.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtgrupoCaretUpdate(evt);
                }
            });

            javax.swing.GroupLayout panelCPTLayout = new javax.swing.GroupLayout(panelCPT);
            panelCPT.setLayout(panelCPTLayout);
            panelCPTLayout.setHorizontalGroup(
                panelCPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCPTLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(txtgrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addGap(4, 4, 4))
            );
            panelCPTLayout.setVerticalGroup(
                panelCPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCPTLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(txtgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            lTipoDoc.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
            lTipoDoc.setForeground(new java.awt.Color(51, 51, 51));
            lTipoDoc.setText("Tipo de Documento");

            cbxTipoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            cbxTipoDocumento.setForeground(new java.awt.Color(51, 51, 51));
            cbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
            cbxTipoDocumento.setEnabled(false);
            cbxTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseReleased(java.awt.event.MouseEvent evt) {
                    cbxTipoDocumentoMouseReleased(evt);
                }
            });
            cbxTipoDocumento.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    cbxTipoDocumentoItemStateChanged(evt);
                }
            });
            cbxTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cbxTipoDocumentoActionPerformed(evt);
                }
            });
            cbxTipoDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    cbxTipoDocumentoKeyPressed(evt);
                }
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    cbxTipoDocumentoKeyTyped(evt);
                }
            });

            lDoc.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
            lDoc.setForeground(new java.awt.Color(51, 51, 51));
            lDoc.setText("Numero de Documento");

            lblNumeroDoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblNumeroDoc.setForeground(new java.awt.Color(51, 51, 51));
            lblNumeroDoc.setText("001-0000000005");

            lDoc1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
            lDoc1.setForeground(new java.awt.Color(51, 51, 51));
            lDoc1.setText("Item");

            panelCPT1.setBackground(new java.awt.Color(255, 255, 255));
            panelCPT1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

            txtCPT.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            txtCPT.setForeground(new java.awt.Color(51, 51, 51));
            txtCPT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            txtCPT.setBorder(javax.swing.BorderFactory.createCompoundBorder());
            txtCPT.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtCPTCaretUpdate(evt);
                }
            });

            btnBuscarCPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos/Búsqueda-25.png"))); // NOI18N
            btnBuscarCPT.setContentAreaFilled(false);
            btnBuscarCPT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnBuscarCPT.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBuscarCPTActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout panelCPT1Layout = new javax.swing.GroupLayout(panelCPT1);
            panelCPT1.setLayout(panelCPT1Layout);
            panelCPT1Layout.setHorizontalGroup(
                panelCPT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCPT1Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(txtCPT)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnBuscarCPT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3))
            );
            panelCPT1Layout.setVerticalGroup(
                panelCPT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCPT1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addGroup(panelCPT1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCPT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(btnBuscarCPT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel36.setBackground(new java.awt.Color(41, 127, 184));
            jPanel36.setPreferredSize(new java.awt.Dimension(0, 2));

            javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
            jPanel36.setLayout(jPanel36Layout);
            jPanel36Layout.setHorizontalGroup(
                jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            jPanel36Layout.setVerticalGroup(
                jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 2, Short.MAX_VALUE)
            );

            jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
            jScrollPane4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
            jScrollPane4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

            tb_CPT.setBorder(javax.swing.BorderFactory.createCompoundBorder());
            tb_CPT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            tb_CPT.setForeground(new java.awt.Color(51, 51, 51));
            tb_CPT.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Item", "Precio", "Cantidad", "IGV"
                }
            ));
            tb_CPT.setGridColor(new java.awt.Color(255, 255, 255));
            tb_CPT.setRowHeight(25);
            tb_CPT.setSelectionBackground(new java.awt.Color(102, 102, 102));
            tb_CPT.getTableHeader().setReorderingAllowed(false);
            tb_CPT.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tb_CPTMouseClicked(evt);
                }
            });
            tb_CPT.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    tb_CPTKeyPressed(evt);
                }
            });
            jScrollPane4.setViewportView(tb_CPT);

            panelNumeros.setBackground(new java.awt.Color(214, 217, 223));
            panelNumeros.setBorder(javax.swing.BorderFactory.createCompoundBorder());

            jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel26.setForeground(new java.awt.Color(51, 51, 51));
            jLabel26.setText("Total a Pagar");

            panelSumaDetalle.setBackground(new java.awt.Color(214, 217, 223));

            jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel39.setForeground(new java.awt.Color(51, 51, 51));
            jLabel39.setText("IGV");

            jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            jLabel28.setForeground(new java.awt.Color(51, 51, 51));
            jLabel28.setText("Subtotal");

            txtTotal2.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
            txtTotal2.setForeground(new java.awt.Color(51, 51, 51));
            txtTotal2.setText("0");

            txtTotal3.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
            txtTotal3.setForeground(new java.awt.Color(51, 51, 51));
            txtTotal3.setText("0");

            javax.swing.GroupLayout panelSumaDetalleLayout = new javax.swing.GroupLayout(panelSumaDetalle);
            panelSumaDetalle.setLayout(panelSumaDetalleLayout);
            panelSumaDetalleLayout.setHorizontalGroup(
                panelSumaDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSumaDetalleLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel28)
                    .addGap(18, 18, 18)
                    .addComponent(txtTotal2)
                    .addGap(104, 104, 104)
                    .addComponent(jLabel39)
                    .addGap(32, 32, 32)
                    .addComponent(txtTotal3)
                    .addContainerGap())
            );
            panelSumaDetalleLayout.setVerticalGroup(
                panelSumaDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTotal3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            txtTotal.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
            txtTotal.setForeground(new java.awt.Color(51, 51, 51));
            txtTotal.setText("0");

            txtTotal1.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
            txtTotal1.setForeground(new java.awt.Color(51, 51, 51));
            txtTotal1.setText("S/. ");

            javax.swing.GroupLayout panelNumerosLayout = new javax.swing.GroupLayout(panelNumeros);
            panelNumeros.setLayout(panelNumerosLayout);
            panelNumerosLayout.setHorizontalGroup(
                panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNumerosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelSumaDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(81, 81, 81)
                    .addComponent(jLabel26)
                    .addGap(65, 65, 65)
                    .addComponent(txtTotal1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtTotal)
                    .addContainerGap(65, Short.MAX_VALUE))
            );
            panelNumerosLayout.setVerticalGroup(
                panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNumerosLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addGroup(panelNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelSumaDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );

            panelEliminacion.setBackground(new java.awt.Color(255, 51, 51));

            btnEliminarDetalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            btnEliminarDetalle.setForeground(new java.awt.Color(240, 240, 240));
            btnEliminarDetalle.setText("Eliminar Este Registro ?");
            btnEliminarDetalle.setContentAreaFilled(false);
            btnEliminarDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnEliminarDetalle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
            btnEliminarDetalle.setIconTextGap(30);
            btnEliminarDetalle.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEliminarDetalleActionPerformed(evt);
                }
            });

            noeli5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            noeli5.setForeground(new java.awt.Color(240, 240, 240));
            noeli5.setText("No");
            noeli5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
            noeli5.setContentAreaFilled(false);
            noeli5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            noeli5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            noeli5.setIconTextGap(30);
            noeli5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    noeli5ActionPerformed(evt);
                }
            });

            eli5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            eli5.setForeground(new java.awt.Color(240, 240, 240));
            eli5.setText("Si");
            eli5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
            eli5.setContentAreaFilled(false);
            eli5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            eli5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            eli5.setIconTextGap(30);
            eli5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    eli5ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout panelEliminacionLayout = new javax.swing.GroupLayout(panelEliminacion);
            panelEliminacion.setLayout(panelEliminacionLayout);
            panelEliminacionLayout.setHorizontalGroup(
                panelEliminacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEliminacionLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnEliminarDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(eli5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(noeli5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            panelEliminacionLayout.setVerticalGroup(
                panelEliminacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEliminacionLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(panelEliminacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarDetalle)
                        .addComponent(eli5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(noeli5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6))
            );

            lDoc2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
            lDoc2.setForeground(new java.awt.Color(51, 51, 51));
            lDoc2.setText("Cantidad");

            panelCPT2.setBackground(new java.awt.Color(255, 255, 255));
            panelCPT2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

            txtgrupo1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
            txtgrupo1.setForeground(new java.awt.Color(51, 51, 51));
            txtgrupo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            txtgrupo1.setBorder(null);
            txtgrupo1.addCaretListener(new javax.swing.event.CaretListener() {
                public void caretUpdate(javax.swing.event.CaretEvent evt) {
                    txtgrupo1CaretUpdate(evt);
                }
            });

            javax.swing.GroupLayout panelCPT2Layout = new javax.swing.GroupLayout(panelCPT2);
            panelCPT2.setLayout(panelCPT2Layout);
            panelCPT2Layout.setHorizontalGroup(
                panelCPT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCPT2Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(txtgrupo1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGap(4, 4, 4))
            );
            panelCPT2Layout.setVerticalGroup(
                panelCPT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCPT2Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(txtgrupo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lTipoDoc)
                        .addComponent(lDoc)
                        .addComponent(jLabel2)
                        .addComponent(lDoc1))
                    .addGap(50, 50, 50)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelCPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumeroDoc)
                        .addComponent(cbxTipoDocumento, 0, 242, Short.MAX_VALUE)
                        .addComponent(panelCPT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addComponent(lDoc2)
                    .addGap(33, 33, 33)
                    .addComponent(panelCPT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jScrollPane4)
                .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addComponent(panelEliminacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panelCPT1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(panelCPT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lTipoDoc)
                                .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lDoc)
                                .addComponent(lblNumeroDoc))
                            .addGap(18, 18, 18)
                            .addComponent(lDoc1))
                        .addComponent(lDoc2)
                        .addComponent(panelCPT2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addGap(0, 0, 0)
                    .addComponent(panelEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(panelNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0))
            );

            jTabbedPane1.addTab("tab2", jPanel4);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                        .addComponent(panelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, Short.MAX_VALUE)))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(panelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedasCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBusquedasCaretUpdate

    }//GEN-LAST:event_txtBusquedasCaretUpdate

    private void txtBusquedasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedasKeyTyped

    }//GEN-LAST:event_txtBusquedasKeyTyped

    private void btnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPacienteActionPerformed

    }//GEN-LAST:event_btnBuscarPacienteActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed

    }//GEN-LAST:event_btnListaActionPerformed

    private void btnCorrectoSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrectoSiActionPerformed

    }//GEN-LAST:event_btnCorrectoSiActionPerformed

    private void btnCorrectoSiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCorrectoSiKeyPressed

    }//GEN-LAST:event_btnCorrectoSiKeyPressed

    private void btnCorrectoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrectoNoActionPerformed
        panelMensaje.setVisible(false);
    }//GEN-LAST:event_btnCorrectoNoActionPerformed

    private void txtgrupoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtgrupoCaretUpdate

    }//GEN-LAST:event_txtgrupoCaretUpdate

    private void cbxTipoDocumentoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxTipoDocumentoMouseReleased

    }//GEN-LAST:event_cbxTipoDocumentoMouseReleased

    private void cbxTipoDocumentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoDocumentoItemStateChanged

    }//GEN-LAST:event_cbxTipoDocumentoItemStateChanged

    private void cbxTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoDocumentoActionPerformed

    }//GEN-LAST:event_cbxTipoDocumentoActionPerformed

    private void cbxTipoDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxTipoDocumentoKeyPressed

    }//GEN-LAST:event_cbxTipoDocumentoKeyPressed

    private void cbxTipoDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxTipoDocumentoKeyTyped

    }//GEN-LAST:event_cbxTipoDocumentoKeyTyped

    private void txtCPTCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCPTCaretUpdate

    }//GEN-LAST:event_txtCPTCaretUpdate

    private void btnBuscarCPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCPTActionPerformed

    }//GEN-LAST:event_btnBuscarCPTActionPerformed

    private void tb_CPTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_CPTMouseClicked

    }//GEN-LAST:event_tb_CPTMouseClicked

    private void tb_CPTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_CPTKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_CPTKeyPressed

    private void btnEliminarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDetalleActionPerformed

    }//GEN-LAST:event_btnEliminarDetalleActionPerformed

    private void noeli5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noeli5ActionPerformed
        panelEliminacion.setVisible(false);
    }//GEN-LAST:event_noeli5ActionPerformed

    private void eli5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eli5ActionPerformed

    }//GEN-LAST:event_eli5ActionPerformed

    private void txtgrupo1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtgrupo1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrupo1CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caja_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caja_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caja_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caja_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caja_Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensaje4;
    private javax.swing.JButton btnBuscarCPT;
    private javax.swing.JButton btnBuscarPaciente;
    private javax.swing.JButton btnCorrectoNo;
    private javax.swing.JButton btnCorrectoSi;
    private javax.swing.JButton btnEliminarDetalle;
    public static javax.swing.JButton btnImprimir;
    public static javax.swing.JButton btnLista;
    public static javax.swing.JButton btnNuevo;
    public static javax.swing.JButton btneliminar;
    private javax.swing.JComboBox cbxTipoDocumento;
    private javax.swing.JButton eli5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lDoc;
    private javax.swing.JLabel lDoc1;
    private javax.swing.JLabel lDoc2;
    private javax.swing.JLabel lTipoDoc;
    public static javax.swing.JLabel lblNumeroDoc;
    private javax.swing.JLabel lbldetalle;
    private javax.swing.JButton noeli5;
    private javax.swing.JPanel panelCPT;
    private javax.swing.JPanel panelCPT1;
    private javax.swing.JPanel panelCPT2;
    private javax.swing.JPanel panelEliminacion;
    private javax.swing.JPanel panelMensaje;
    private javax.swing.JPanel panelNumeros;
    private javax.swing.JPanel panelSumaDetalle;
    private javax.swing.JTable tb_CPT;
    public static javax.swing.JTextField txtBusquedas;
    public static javax.swing.JTextField txtCPT;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtTotal1;
    private javax.swing.JLabel txtTotal2;
    private javax.swing.JLabel txtTotal3;
    private javax.swing.JLabel txtape;
    public static javax.swing.JTextField txtgrupo;
    public static javax.swing.JTextField txtgrupo1;
    // End of variables declaration//GEN-END:variables
}
